spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eac?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true #日志显示sql语句


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080

springdoc:
  # 不要乱动下面的（
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /api
#    enabled: true
